apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: apache2
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apache2
    spec:
      containers:
      - name: apache2
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /var/log/apache2
          name: apache2-claim0
        - mountPath: /var/www
          name: applications-claim0
      restartPolicy: Always
      volumes:
      - name: apache2-claim0
        persistentVolumeClaim:
          claimName: apache2-claim0
      - name: applications-claim0
        persistentVolumeClaim:
          claimName: applications-claim0
status: {}
