apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: applications
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: applications
    spec:
      containers:
      - image: tianon/true
        name: applications
        resources: {}
        volumeMounts:
        - mountPath: /var/www
          name: applications-claim0
      restartPolicy: Always
      volumes:
      - name: applications-claim0
        persistentVolumeClaim:
          claimName: applications-claim0
status: {}
