apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: influx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: influx
    spec:
      containers:
      - env:
        - name: ADMIN_USER
          value: admin
        - name: INFLUXDB_ADMIN_ENABLED
          value: "true"
        - name: INFLUXDB_DATA_QUERY_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_INIT_PWD
          value: admin
        - name: INFLUXDB_META_LOGGING_ENABLED
          value: "false"
        - name: INFLUXDB_REPORTING_DISABLED
          value: "true"
        - name: PRE_CREATE_DB
          value: sensordata;telegraf
        name: influx
        ports:
        - containerPort: 8083
        - containerPort: 8086
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: laradock-influx
      restartPolicy: Always
      volumes:
      - name: laradock-influx
        persistentVolumeClaim:
          claimName: laradock-influx
status: {}
