apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mosquitto
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mosquitto
    spec:
      containers:
      - name: mosquitto
        ports:
        - containerPort: 1883
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /mqtt/config
          name: laradock-mosquitto
        - mountPath: /mqtt/log
          name: laradock-mosquitto
        - mountPath: /mqtt/data
          name: laradock-mosquitto
      restartPolicy: Always
      volumes:
      - name: laradock-mosquitto
        persistentVolumeClaim:
          claimName: laradock-mosquitto
      - name: laradock-mosquitto
        persistentVolumeClaim:
          claimName: laradock-mosquitto
      - name: laradock-mosquitto
        persistentVolumeClaim:
          claimName: laradock-mosquitto
status: {}
