apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: php-fpm
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php-fpm
    spec:
      containers:
      - env:
        - name: PHP_IDE_CONFIG
          value: serverName=laravel
        name: php-fpm
        resources: {}
        volumeMounts:
        - mountPath: /var/www
          name: applications-claim0
      restartPolicy: Always
      volumes:
      - name: applications-claim0
        persistentVolumeClaim:
          claimName: applications-claim0
status: {}
