apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: phpmyadmin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: phpmyadmin
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          value: homestead
        - name: PMA_ARBITRARY
          value: "1"
        - name: MYSQL_PASSWORD
          value: secret
        - name: MYSQL_ROOT_PASSWORD
          value: root
        name: phpmyadmin
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
