apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: spulserver
  name: spulserver
spec:
  ports:
  - name: "9007"
    port: 9007
    targetPort: 9007
  - name: "9008"
    port: 9008
    targetPort: 9008
  selector:
    io.kompose.service: spulserver
status:
  loadBalancer: {}
