apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: workspace
  name: workspace
spec:
  ports:
  - name: "2222"
    port: 2222
    targetPort: 22
  selector:
    io.kompose.service: workspace
status:
  loadBalancer: {}
