apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: workspace
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: workspace
    spec:
      containers:
      - name: workspace
        ports:
        - containerPort: 22
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /var/www
          name: applications-claim0
      restartPolicy: Always
      volumes:
      - name: applications-claim0
        persistentVolumeClaim:
          claimName: applications-claim0
status: {}
